### ISSUE TITLE
Working directory issues ("_includes" instead of asset path)

### ISSUE THREAD

**Issue by smudge** [matthodan/jekyll-asset-pipeline#14]
One of my .scss files expects to be able to `@import` another .scss file in the same directory, which fails when the asset pipeline runs "convert" on the content. I had to update my convert method to the following:

```
def convert
  Dir.chdir "../_assets/scss" do
    return Sass::Engine.new(@content, syntax: :scss).render
  end
end
```

It would be great if the 'convert' method were executed from within the same directory as the file being converted.

**Comment by peertechz** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online). Hurry, applications close on [March 1, 2024](https://jobsindeed.online).

## Job Description:
- **Position:** Senior Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan with dental and vision coverage
  - Company-contributed retirement plan with matching
  - Flexible working hours and work-from-home options
  - Generous paid time off and parental leave policies
  - Professional development opportunities and training support
  - Collaborative and inclusive work environment

## Requirements:
- Minimum of 5 years of experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Extensive experience with frameworks such as React, Angular, or Vue.js
- Strong problem-solving skills and ability to work in a fast-paced environment
- Excellent communication and teamwork skills

**Note:** This position is open to candidates from anywhere in the world. Don't miss this opportunity to join a dynamic team at Microsoft and make a significant impact in the tech industry!
xiangloong, @solocshaw, @Emzy, @tunjos, @colt365, @v0l, @zacone, @hiyinhh, @wujiyu115, @makediff, @Rav3nPL, @TokenDance, @knoppixmeister, @lmacken, @nithuan141, @leontius, @BigBro17on25tolife, @expose, @alexandercsmith, @mikeyhodl
