### ISSUE TITLE
Support Jekyll 1.0

### ISSUE THREAD

**Issue by liamzebedee** [matthodan/jekyll-asset-pipeline#30]
Currently the rubygem runtime dependency is jekyll ~> 0.12. [Jekyll 1](http://blog.parkermoore.de/2013/05/06/jekyll-1-dot-0-released/) was just released, and it doesn't look like any of the changes have broken asset pipeline, so really all is needed is to change the dependency version.

**Comment by janosrusiczki** [comment]
We now support Jekyll 3.5.
