### ISSUE TITLE
Link to the latest gem.  https://github.com/kitsched/japr

### ISSUE THREAD

**Issue by lawwantsin** [matthodan/jekyll-asset-pipeline#46]
Hey, can you link to the current asset pipeline gem https://github.com/kitsched/japr repo instead of leaving this to confuse everyone?  This gem only works with Jekyll 0.12.1.  Wasted a few hours of my life.

**Comment by sethherr** [comment]
:+1:, I also wasted time on this.

**Comment by janosrusiczki** [comment]
FYI, I just updated my fork to be compatible with Jekyll 3.5.

**Comment by janosrusiczki** [comment]
JAPR has been merged back here.
