### ISSUE TITLE
Support for Jekyll 3.5

### ISSUE THREAD

**Issue by y0gzah** [matthodan/jekyll-asset-pipeline#48]
Solvable by fixing the AssetTag class 'render' method.
There has been a structural change in Jekyll's render context.

**Comment by taras-danyliuk** [comment]
Hi @y0gzah, can you explain how it can be fixed?

**Comment by janosrusiczki** [comment]
Jekyll 3.5 is supported in [my fork](https://github.com/janosrusiczki/japr).

**Comment by janosrusiczki** [comment]
And now as I merged my fork, it is also supported here.
